Implementa mural de avisos
TreinaDev/condominions pull request #109
Opened 2024-07-18 06:23 UTC by lucasobx

Mural de avisos

2024-07-19 00:47 UTC, mbellucio approved these changes
Bom trabalho, aprovado! Deixei apenas algumas sugestões.

2024-07-19 00:47 UTC, mbellucio commented on app/controllers/application_controller.rb
Aqui fica apenas uma observação: Ao invez de usarem o application controller, talvez não seria melhor se criassem outro controller que herde de application controller, e nos controllers que necessitam dessas autorizações vocês herdassem desse novo controller customizado? Para fins de organização...

2024-07-19 00:47 UTC, mbellucio commented on app/views/announcements/show.html.erb
> +    <p><strong>Atualizado em:</strong> <%= @announcement.updated_at.strftime('%d/%m/%Y %H:%M') %></p>
Aqui não deveriam usar o I18n para formatar esta data?

2024-07-19 00:47 UTC, mbellucio commented on app/views/condos/show.html.erb
É comum de precisarmos usar esses nomes como 'Mural de Avisos' etc... mais vezes na aplicação, talvez valeria a pena padronizar usando o I18n

2024-07-20 02:41 UTC, Vinigperuzzi commented on app/controllers/application_controller.rb
A gente fez uma super mega ultra refatoração em uma outra branch que vai entrar antes dessa que faz justamente isso.

Realmente o controller tá estranho, mas não chega a ser assunto dessa branch em específico, mas um problema geral.

2024-07-20 02:41 UTC, Vinigperuzzi commented on app/views/condos/show.html.erb
Realmente

2024-07-20 18:44 UTC, cellaaleo commented on app/models/condo.rb
> +  def three_more_recent_announcements
Acho que o termo correto aqui seria 'most' no lugar de 'more': 'three_most_recent_announcements'

2024-07-20 19:10 UTC, cellaaleo approved these changes
Mto bom!

2024-07-20 19:29 UTC, lucasobx commented on app/models/condo.rb
> +  def three_more_recent_announcements
Corrigido!

2024-07-20 19:59 UTC, lucasobx commented on app/views/announcements/show.html.erb
> +    <p><strong>Atualizado em:</strong> <%= @announcement.updated_at.strftime('%d/%m/%Y %H:%M') %></p>
Corrigido!

2024-07-20 20:13 UTC, ruliancruz requested changes
O PR está bem escrito e completo. As telas estão muito bonitas e seguem bem o padrão da aplicação, também gostei da UX. Mas tenho algumas dúvidas que acredito serem importantes de serem analisadas antes de realizarmos o merge com a main, por isso vou esperar vocês responderem antes de aprovar.

2024-07-20 20:13 UTC, ruliancruz commented on spec/system/announcements/manager_edits_announcements_spec.rb
Não está faltando um teste para verificar se o morador não consegue editar um aviso?

Entendam que existam testes de requisição validado se ele consegue executar a atualização, mas não vi algum que verifique se ele tem acesso à página de edição.

2024-07-20 20:26 UTC, lucasobx commented on app/controllers/announcements_controller.rb
> +  end
Tem razão. Unimos os dois métodos.

2024-07-20 20:39 UTC, lucasobx commented on spec/spec_helper.rb
Esses comentários foram gerados pelo Action Text.

2024-07-20 21:24 UTC, lucasobx commented on spec/requests/announcement_request_spec.rb
> +    end
Modificamos para testar que um usuário não autenticado é redirecionado para a página de login.

2024-07-20 21:29 UTC, lucasobx commented on spec/requests/announcement_request_spec.rb
> +    end
Criamos contextos para separar os testes de administrador e morador.

2024-07-20 21:31 UTC, lucasobx commented on spec/system/announcements/manager_registers_new_announcement_spec.rb
Teste feito!

2024-07-20 21:40 UTC, lucasobx commented on spec/system/announcements/manager_edits_announcements_spec.rb
Teste feito!

2024-07-20 22:03 UTC, lucasobx commented on app/views/announcements/index.html.erb
> +                <p style="margin: 0; font-size: 14px;">Visualizar</p> <i class="bi bi-search ms-1"></i>
Corrigido!

2024-07-20 22:08 UTC, lucasobx commented on app/views/condos/dashboard/_announcement_board.html.erb
> +          <p style="margin: 0; font-size: 14px;">Visualizar</p> <i class="bi bi-search ms-1"></i>
Corrigido!

2024-07-20 23:01 UTC, ruliancruz approved these changes

2024-07-20 23:10 UTC, ruliancruz approved these changes

2024-07-20 23:11 UTC, merged