Multiplas propriedades residente
TreinaDev/condominions pull request #84
Opened 2024-07-11 03:47 UTC by DaniloRibeiro07

2024-07-12 22:43 UTC, RyanOxon approved these changes
PR bem grande, dificil de revisar. Acredito estar tudo ok, mas seria bom esperar mais opnioes do resto do time antes de mergar

2024-07-13 04:40 UTC, ruliancruz requested changes
Está confuso, não entendi totalmente o que está sendo feito no que foi implementado, mas deixei alguns comentários no que eu consegui.

Entendo que é um desafio deixar claro um PR tão grande, que envolve refatorar diversas partes da aplicação que são necessárias para a nova alteração nas regras de negócio, tanto que minha revisão acabou ficando grande também. Mas acredito que alterando algumas partes do código vocês possam tornar mais fácil para o resto do time entender o que vocês estão implementando.

Também acredito que existam ajustes a serem feitos na descrição do PR, os quais podem deixar mais claro o que está sendo implementado.

Por exemplo na segunda linha da introdução:
`Como administrador, deve ser possível adicionar propriedades ao morador e definir a sua residência;`
Deve ser possível ou agora é possível? Isso se encaixaria melhor como objetivo.

Seria interessante escrever a introdução de forma que deixe claro o que foi alterado em comparação ao que existia antes, talvez escrever em texto corrido possa ajudar.

Também poderiam ajustar os objetivos para dialogar mais com o título do PR/issue, talvez adicionando até mais alguns, para termos uma linha mais clara de por onde seguir.

Quanto aos detalhes, talvez descrevendo um pouco mais o que está sendo implementado possa ajudar a tornar o fluxo mais inteligível.

A respeito do código, acredito que valha a pena analisar o que comentei e refatorar o que acharem pertinente e ter mais alguma revisão para que então possamos fazer uma revisão mais precisa e segura. Por isso não vou deixar aprovado por enquanto.

2024-07-13 14:24 UTC, Vinigperuzzi commented on app/models/resident.rb
> +  enum status: { not_owner: 0, not_tenant: 1, mail_not_confirmed: 2, mail_confirmed: 3 }
Isso é  a progressão de status do morador, para poder gerar aquele link clicável no aviso de cadastro incompleto. Seguimos a mesma ideia das Torres só que aqui é mais complexo.

2024-07-13 14:27 UTC, Vinigperuzzi commented on app/controllers/owners_controller.rb
> +    @resident.not_tenant! if @resident.not_owner?
Pode, o fato de clicar no botão 'não reside neste condomínio ' também atualiza esse status. O que essa etapa testa é  se a segunda etapa do cadastro já foi concluída para permitir o avanço da terceira e o envio do e-mail.

2024-07-13 14:31 UTC, Vinigperuzzi commented on app/controllers/tenants_controller.rb
> +    elsif unit.tenant
Esse método já est completamente rebatizado em outra branch que trouxe 3 situações de mensagens agora.  Assim que for mergeado já  ai trazer a atualização.  Inclusive precisamos de 3 outros métodos para não cair no método muito grande do rubocop

2024-07-15 02:05 UTC, Vinigperuzzi commented on README.md
> +Retorna 412 se o CPF não for válido para consulta.
É verdade, refeito

2024-07-15 02:38 UTC, Vinigperuzzi commented on app/controllers/residents_controller.rb
> +    return tower.floors[params['resident']['floor'].to_i - 1 ] if tower
Como falamos na call, vou refatorar na última rebranch

2024-07-15 02:40 UTC, Vinigperuzzi commented on spec/system/resident/manager_register_new_resident_spec.rb
> +  it 'with incomplete data INCOMPLETO' do
Ah cara, esse incompleto, era porque o teste estava incompleto, para não esquecermos de voltar nele. De fato, não esquecemos do teste, só do it

2024-07-15 02:43 UTC, Vinigperuzzi commented on spec/system/resident/manager_sets_resident_as_owner_spec.rb
> +  end
Corrigido, ctrl c + ctrl v do mal

2024-07-15 02:44 UTC, Vinigperuzzi commented on spec/system/resident/manager_sets_resident_as_owner_spec.rb
> +  it 'and choose an existent unit (success)' do
resolvido!

2024-07-15 02:45 UTC, Vinigperuzzi commented on spec/system/resident/manager_sets_resident_as_owner_spec.rb
> +    unidade11 = tower.floors[0].units[0]
Nenhum, cansaço mesmo.

2024-07-15 02:46 UTC, Vinigperuzzi commented on app/controllers/tenants_controller.rb
> +  end
Refatoramos na branch do e-mail!

2024-07-15 02:52 UTC, Vinigperuzzi commented on app/controllers/tenants_controller.rb
> +  end
feito

2024-07-15 03:02 UTC, Vinigperuzzi commented on app/controllers/tenants_controller.rb
> +    end
Certo, não refiz por acreditar que essa progressão de status será feita por um método mais condizente na branch das unidades não poderem ter morador antes de proprietário.

2024-07-15 03:02 UTC, Vinigperuzzi commented on app/views/owners/new.html.erb
> +                <h5 class="card-title">Condomínio: <%= unit.condo.name %></h5>
feito

2024-07-15 03:03 UTC, Vinigperuzzi commented on config/routes.rb
> +    resources :tenants, only:[:new, :create], on: :collection
Certo, na linha 11 também

2024-07-15 03:04 UTC, Vinigperuzzi commented on spec/requests/manager_set_owner_spec.rb
> +    post resident_owners_path(resident), params: { floor_id: '15' }
OK

2024-07-15 03:18 UTC, ruliancruz approved these changes
Aprovado! Olhei as mudanças aqui e também conversei com vocês em chamada, então acredito que esteja tudo alinhado.

2024-07-15 03:42 UTC, ruliancruz approved these changes

2024-07-15 03:43 UTC, merged